### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by joket1999** [yinhaibo01/unicode-loader#1]
The index.js:

``` javascript
var mNames = ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月', ''];

module.exports = mNames;

```

The webpack.js:

``` javascript
var path = require('path');
module.exports = {
    entry: [
        './app/index'
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'app.js',
        chunkFilename: '[chunkhash].js',
        publicPath: '/'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'unicode-loader',
            }
        ]
    }
};
```

The packaged file:

``` javascript
!function(r){function t(e){if(o[e])return o[e].exports;var n=o[e]={exports:{},id:e,loaded:!1};return r[e].call(n.exports,n,n.exports,t),n.loaded=!0,n.exports}var o={};return t.m=r,t.c=o,t.p="/",t(0)}([function(r,t,o){r.exports=o(1)},function(r,t){var o=["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月",""];r.exports=o}]);
```

**Comment by yinhaibo01** [comment]
You can get the right content without uglify.
Now the uglify convert the '\u4e00\u6708' to '一月'.
So you should add a parameter for uglify : --beautify "beautify=false,ascii-only=true"
Then you can get the right string.
But I don't know how to pass this parameter in webpack to uglify.

**Comment by yinhaibo01** [comment]
If some other issues, contact me.

**Comment by joket1999** [comment]
I found a way to config it on the official website.
'UglifyJS options:
...
output: an object providing options for UglifyJS’ OutputStream - see the OutputStream [source](https://github.com/mishoo/UglifyJS2/blob/master/lib/output.js) for options and defaults.'

``` javascript
new webpack.optimize.UglifyJsPlugin({
    compress: {
        warnings: false
    },
    output: {
        ascii_only: true,
        beautify: false
    }
})
```

But there seems to be a bug. Options.output doesn't work. I debugged it and found the ‘UglifyJsPlugin’ function([source](https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js)) has been called twice on each file. The first result could be covered with the second

**Comment by yinhaibo01** [comment]
I have read the UglifyPlugin source code, and I didn't found how to pass this kind of options.
And I have reported a bug to uglify, but they can not understand me.
You could report another one :)

**Comment by yinhaibo01** [comment]
Now my way to resolve it: First only do webpack. then call the uglify in command lline to do this.
Command line is correct, run it in node.

**Comment by dangshuaiwei** [comment]
How did the problem finally be solved
